framework:
    workflows:
        article:
            type: workflow
            marking_store:
                type: method
            supports:
                - App\Entity\Article
            initial_marking: draft
            places:
                draft:
                submitted:
                waiting for payment:
                waiting for moderation:
                denied:
                ready to publish:
                ready to unpublish:
            transitions:
                free submit:
                    from: [draft]
                    to:   [submitted]
                submit:
                    from: [draft]
                    to:   [waiting for payment]

                pay:
                    from: waiting for payment
                    to:   submitted

                auto validate:
                    from: submitted
                    to:   [ready to publish, waiting for moderation]

                request moderation:
                    from: submitted
                    to: waiting for moderation
                approve:
                    from: waiting for moderation
                    to:   ready to publish
                deny:
                    from: waiting for moderation
                    to:   denied
                deny after published:
                    from: [denied, ready to publish]
                    to:   ready to unpublish
                second deny:
                    from: [denied]
                    to:   ready to unpublish

                update:
                    from: ready to publish
                    to: [waiting for moderation, ready to publish]

                expire:
                    from: ready to publish
                    to: ready to unpublish

                reactivate:
                    from: ready to unpublish
                    to: draft
            audit_trail: true


# framework:
#     workflows:
#         article:
#             type: workflow
#             marking_store:
#                 type: method
#             supports:
#                 - App\Entity\Article
#             places:
#                 draft:
#                     metadata:
#                         title: Draft
#                 waiting for journalist:
#                     metadata:
#                         title: Waiting for Journalist review
#                 approved by journalist:
#                     metadata:
#                         title: Approved By Journalist
#                 wait for spellchecker:
#                     metadata:
#                         title: Waiting for Spellchecker review
#                 approved by spellchecker:
#                     metadata:
#                         title: Approved By Spellchecker
#                 published: ~
#             transitions:
#                 request review:
#                     guard: "is_fully_authenticated()"
#                     from: draft
#                     to:
#                         - waiting for journalist
#                         - wait for spellchecker
#                     metadata:
#                         title: Do you want a Review?
#                 journalist approval:
#                     guard: "is_granted('ROLE_JOURNALIST')"
#                     from: waiting for journalist
#                     to: approved by journalist
#                     metadata:
#                         title: Do you valid the article?
#                 spellchecker approval:
#                     guard: "is_fully_authenticated() and is_granted('ROLE_SPELLCHECKER')"
#                     from: wait for spellchecker
#                     to: approved by spellchecker
#                     metadata:
#                         title: Do you valid the spell check?
#                 publish:
#                     guard: "is_fully_authenticated()"
#                     from:
#                         - approved by journalist
#                         - approved by spellchecker
#                     to: published
#                     metadata:
#                         title: Do you want to publish?
#             metadata:
#                 title: Workflow to manager article
#             audit_trail: true
